// Declarations for static image imports (`import logo from './logo.png'`).
//
// next-env.d.ts already references these, but it is gitignored and only
// regenerated by `next build` — and it also imports .next/types/routes.d.ts,
// which doesn't exist until a build has run. CI typechecks before building, so
// it needs this reference from a committed file instead.
/// <reference types="next/image-types/global" />
